[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo/data
db_name = 
db_host = odoo19-db
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8069
gevent_port = 8072
http_interface = 0.0.0.0
list_db = False
# logfile = /var/lib/odoo/data/odoo-server.log
proxy_mode = True
server_wide_modules = base,web
without_demo = True
workers = 4

